Fix decimal parsing using CultureInfo.InvariantCulture, fixes #68
sebastienros/parlot pull request #70
Opened 2022-01-31 11:12 UTC by aviciano

This PR fixes #68.

2022-03-16 14:27 UTC, sebastienros commented
Can't find the button to trigger the build :/

2022-03-16 14:30 UTC, lahma approved these changes
Testing approve

2022-03-16 14:35 UTC, lahma commented
GitHub has issues, https://www.githubstatus.com/

2022-08-27 18:56 UTC, hishamco requested changes
LGTM except a tiny comment

2022-08-27 18:56 UTC, hishamco commented on test/Parlot.Tests/Calc/Interpreter.cs
> +    using System.Globalization;
Move the using above the namespace

2022-08-27 18:56 UTC, hishamco commented on test/Parlot.Tests/Calc/Parser.cs
> +    using System.Globalization;
Move the using above the namespace

2022-08-27 18:57 UTC, hishamco commented
@aviciano can you close and re-open the PR to trigger the build

2022-08-31 18:38 UTC, hishamco commented
Seems everything is fine, I think it's ready to merge

2022-09-16 21:45 UTC, merged